### ISSUE TITLE
Times are parsed in the wrong time zone.

### ISSUE THREAD

**Issue by calleluks** [linduxed/rmnd.io#13]
Using the Stockholm time zone, adding a reminder at 20:00 creates one at 21:00.

**Comment by calleluks** [comment]
This is still happening. I have played around in an attempt of fixing it but I can't get Chronic to parse both absolute and relative times correctly in the current time zone.

**Comment by calleluks** [comment]
@talltorp Could you try this out, again? It should be fixed with the new time parser introduced in f86643819d8beebefe8dbfe1a8f764565dcba788.

**Comment by talltorp** [comment]
Yea, that seems to fix it!

**Comment by calleluks** [comment]
Cool! Thanks for trying it out.
